### ISSUE TITLE
Standardise formatting

### ISSUE THREAD

**Issue by Lextuga007** [MLCSU/MLCSUr#2]
The code runs over 80 characters which can be hard to read on different screens (laptops for example) and I recommend using the package {lintr} to help highlight where these occur. It'll also highlight other issues like global function definitions for things like %>%:

```
usethis::use_pipe()
```
Another package that is also useful for code standardisation is {styler} which applies the tidyverse formatting. I find this useful to apply after I've written out my code so I don't necessarily have to remember the correct spacing - it does it for me.

Both packages can be installed from CRAN and change RStudio so they can be run from the Add in menu which is useful. There may be a few changes in git from running these package and it might be useful to do them as individual pull requests, linking them to this issue for reference. 

Issues can have checklists so to summarise this issue:

- [x] apply {lintr}
- [x] apply {styler}
- [x] add pipe as a dependency

**Comment by ScottJohnson2** [comment]
Thanks Zoe, this took me longer than it should have done this morning but it appears to have all worked. Much appreciated

**Comment by Lextuga007** [comment]
Well done! Things get a bit easier with practice and this looks great 🏆
